// This file is automatically generated. Do not edit.

#ifndef __ZDEFEND_LICENSE_KEY_NAMES_H__
#define __ZDEFEND_LICENSE_KEY_NAMES_H__
    #import <Foundation/Foundation.h>

    typedef NS_ENUM(NSInteger, ZDefendLicenseKeyNames) {
        LICENSE_KEY_START = 0,
        LICENSE_KEY_ISS_DEV = LICENSE_KEY_START,
        LICENSE_KEY_ISS_DEVELOPMENT,
        LICENSE_KEY_CYBERSECUREAPP_IOS_UAT,
        LICENSE_KEY_CYBERSECUREAPP_IOS,
        LICENSE_KEY_LIMIT
    };
    #define ZDefendLicenseKeyNamesValues @[ @"LICENSE_KEY_ISS_DEV", @"LICENSE_KEY_ISS_DEVELOPMENT", @"LICENSE_KEY_CYBERSECUREAPP_IOS_UAT", @"LICENSE_KEY_CYBERSECUREAPP_IOS", ];

#endif
